### ISSUE TITLE
Description seems to include info for another plugin

### ISSUE THREAD

**Issue by colintedford** [jamespeachh/Three-Noun-Prompts#1]
This sentence seems to describe a different plugin: "This is a plugin intended to connect you and your friend's notes offline."

**Comment by jamespeachh** [comment]
I can see how you thought that, especially because there is no literal connection.  This to me meant that the notes would be essentially connected in the sense that they would both produce the same prompts.  Nevertheless, I updated the wording to hopefully alleviate any future confusion.  Thank you for the input!
